### PR TITLE
🐛 Fix failing Scorecard action

### PR DESCRIPTION
**Pull request by azeemshaikh38**
## Description

This PR fixes https://github.com/ossf/scorecard-action/issues/784

## How Has This Been Tested?

Tested on my fork - https://github.com/azeemshaikh38/honeybot/actions/workflows/scorecards.yml

## Additional context

Add any other context or screenshots about the pull request here.

## Checklist

- [x] I have read, understood and followed our [Contributing Guide](https://github.com/pyhoneybot/honeybot/blob/master/CONTRIBUTING.md)
- [x] My code follows the code style of this project
- [x] I have updated the documentation accordingly
- [x] I added my country flag to the `README.md`

## Code of Conduct

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/pyhoneybot/honeybot/blob/master/CODE_OF_CONDUCT.md)

- [x] I agree to follow this project's Code of Conduct

### CODE REVIEW

**Comment by Abdur-rahmaanJ** [comment]
That's sooooo cooooool 💯

**Comment by Abdur-rahmaanJ** [comment]
@azeemshaikh38 On my end it says path repo not found on the badge.

**Comment by azeemshaikh38** [comment]
> @azeemshaikh38 On my end it says path repo not found on the badge.

Does it still say that? I can see the badge correctly displayed on README

**Comment by Abdur-rahmaanJ** [comment]
@azeemshaikh38 All ok now!

**Pull request merged**
