### PR TITLE
Fix plugin errors on startup and keepalive

### LINKED ISSUE #153: [Bug]: Plugin errors on startup and keepalive
### What happened?

**Version**: GitHub `master` branch
**Operating System**: Windows

#### **Steps**:
1. Setup venv
2. `python -m honeybot init`
3. `python -m honeybot run`

#### **Expected behavior**: 
Bot runs without warnings and errors

#### **Additional information**: 
It seems to happen during bot startup (server join) and keepalive (ping from server)

#### **Screenshot**:
WindowsTerminal_7Dvo1jaE3P

### Relevant log output

```python
Loading core
loading plugin: joins
loading plugin: log
loading plugin: uptime
2022-10-04 03:32:25 bot_core INFO - Loaded plugins
---
2022-10-04 03:32:25 bot_core INFO - Plugin.run() takes 4 positional arguments but 5 were given
2022-10-04 03:32:25 bot_core INFO - Plugin.run() takes 4 positional arguments but 5 were given
2022-10-04 03:32:31 bot_core INFO - Plugin.run() takes 4 positional arguments but 5 were given
2022-10-04 03:32:31 bot_core INFO - Plugin.run() takes 4 positional arguments but 5 were given
2022-10-04 03:32:31 bot_core INFO - Plugin.run() takes 4 positional arguments but 5 were given
quack quack! list index out of range
2022-10-04 03:32:37 bot_core INFO - Plugin.run() takes 4 positional arguments but 5 were given
2022-10-04 03:32:37 bot_core INFO - Plugin.run() takes 4 positional arguments but 5 were given
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by MrTanoshii**
## Description

Fixes #153 

## How Has This Been Tested?

Locally

## Checklist

- [x] I have read, understood and followed our [Contributing Guide](https://github.com/pyhoneybot/honeybot/blob/master/CONTRIBUTING.md)
- [x] My code follows the code style of this project
- [ ] I have updated the documentation accordingly
- [ ] I added my country flag to the `README.md`

## Code of Conduct

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/pyhoneybot/honeybot/blob/master/CODE_OF_CONDUCT.md)

- [x] I agree to follow this project's Code of Conduct

### CODE REVIEW

**Comment by MrTanoshii** [comment]
@ogabrielluiz

Did you intend to take credit for hacktoberfest?
I'm fine with closing this one for one of yours if that is the case; please advise.

**Comment by ogabrielluiz** [comment]
I did. Could you do that, please?

**Comment by MrTanoshii** [comment]
> I did. Could you do that, please?

Please make the PR from your fork to this repo (link: https://github.com/pyhoneybot/honeybot/compare/master...ogabrielluiz:honeybot:master )

**Comment by ogabrielluiz** [comment]
The other one I made is invalid?

**Comment by MrTanoshii** [comment]
> The other one I made is invalid?

The other one you made is on your fork (a fork is a copy of a repository)
So you merged it in your own copy but the original did not receive the merge.

You will have to make a Pull Request on here (the original repository)

**Pull request closed without merging**
