### PR TITLE
New feature IMDb

### PR DESCRIPTION
**Pull request by ZoeyKats**
I have written the code for imdb feature, i hope you like it

- [x] I have read, understood and followed our [Contributing Guide](https://github.com/pyhoneybot/honeybot/blob/master/CONTRIBUTING.md)
- [x] My code follows the code style of this project
- [x] I have updated the documentation accordingly
- [x] I added my country flag to the `README.md`

## Code of Conduct

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/pyhoneybot/honeybot/blob/master/CODE_OF_CONDUCT.md)

- [x] I agree to follow this project's Code of Conduct

### CODE REVIEW

**Comment by Abdur-rahmaanJ** [comment]
Hey @ZoeyKats Can you add it to the README? Thanks!

**Comment by ZoeyKats** [comment]
Sure i just did it!

**Comment by MrTanoshii** [comment]
> Sure i just did it!

Hey there, thanks for the contribution!

I see you opened another PR for the `README.md` changes
Can you please merge the two into this one?
You can do so by closing #192 and merges your changes to the same main branch `ZoeyKats:master`.

There's also a few issues with regards to formatting/style

Can you please do the following:
- Run `black main.py`
- Format `README.md` automatically with VS Code or a web tool such as https://codebeautify.org/markdown-formatter

**Comment by ZoeyKats** [comment]
I finished what you asked me to do, I hope everything is ok. Please tell me if there is something else I need to do

**Comment by ZoeyKats** [comment]
I found out I messed up a little bit when I formatted the code. I just committed the correct one. Sorry for any trouble

**Comment by paulosgf** [comment]
@Abdur-rahmaanJ and @MrTanoshii , there are something missing here? Or we already can merge it?

**Comment by paulosgf** [comment]
@ZoeyKats, I'm updating de documentation and then I found a bug complaining that the imdb module is missing. I'm trying to install it, but PyPI has no module named imdb. How I can import it?
Here's the error logs:

`WARNING: autodoc: failed to import module 'main' from module 'plugins.downloaded.movies_imdb'; the following exception was raised:
No module named 'imdb'
`
`$ pip install imdb
ERROR: Could not find a version that satisfies the requirement imdb (from versions: none)
ERROR: No matching distribution found for imdb
`

**Comment by ZoeyKats** [comment]
@paulosgf you can try   pip install cinemagoer , sorry for not mentioning it earlier i had totally forgotten about this issue. I think the package IMDbPY was renamed to cinemagoer that's the reason it changed.

**Comment by paulosgf** [comment]
Can you update your plug-in with this module? Don't forget requirements.txt
Thanks!

**Comment by paulosgf** [comment]
> Can you update your plug-in with this module? Don't forget requirements.txt Thanks!

@ZoeyKats , did you see this message?

**Comment by ZoeyKats** [comment]
@paulosgf hey sorry i just saw this, i'll make sure to change it!

**Pull request merged**
