### PR TITLE
created run.py file to run the bot 

### PR DESCRIPTION
**Pull request by ChristianSchneeweiss**
# brief description of changes
created run.py file to replace main.py as starting point and changed CONTRIBUTING.md to contain the updated procedure for contributing

### CODE REVIEW

**Comment by ChristianSchneeweiss** [comment]
closes issue #14

**Comment by ChristianSchneeweiss** [comment]
Could you elaborate why you reverted this pull request?

**Comment by Abdur-rahmaanJ** [comment]
the other one was before!

**Comment by Abdur-rahmaanJ** [comment]
@ChristianSchneeweiss but we need some help with tests and plugin erros on running. we need to load plugins after connection!

**Pull request merged**
