### PR TITLE
Update honeybot logo link

### PR DESCRIPTION
**Pull request by akankshasainics**
## Description
Update logo link to point to `assets` directory
## How Has This Been Tested?
local repo

## Checklist

- [x] I have read, understood and followed our [Contributing Guide](https://github.com/pyhoneybot/honeybot/blob/master/CONTRIBUTING.md)
- [x] My code follows the code style of this project
- [x] I have updated the documentation accordingly
- [x] I added my country flag to the `README.md`

## Code of Conduct

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/pyhoneybot/honeybot/blob/master/CODE_OF_CONDUCT.md)

- [x] I agree to follow this project's Code of Conduct

### CODE REVIEW

**Review by paulosgf — CHANGES_REQUESTED** [review]
it will be necessary to update the HTML files on gh-pages branch as described in [`https://pyhoneybot.github.io/honeybot/How_Tos/documentation.html` ](https://pyhoneybot.github.io/honeybot/How_Tos/documentation.html) to synchronize the source with our website.

**Comment by akankshasainics** [comment]
But there is no change in HTML files. In the documentation, just the path of the logo in `docs\source\conf.py` is changed, and the logo is copied to the `html\_static` folder same as before. I also tested documentation locally.

**Comment by paulosgf** [comment]
> But there is no change in HTML files. In the documentation, just the path of the logo in `docs\source\conf.py` is changed, and the logo is copied to the `html\_static` folder same as before. I also tested documentation locally.

The command `sphinx-build ../docs/source/ .` did not create new HTML files?

**Comment by akankshasainics** [comment]
> > But there is no change in HTML files. In the documentation, just the path of the logo in `docs\source\conf.py` is changed, and the logo is copied to the `html\_static` folder same as before. I also tested documentation locally.
> 
> The command `sphinx-build ../docs/source/ .` did not create new HTML files?

Yes, The HTML files created by command `sphinx-build ../docs/source/ .` are same, there is no modification in content of HTML files.

**Pull request merged**
